#!/usr/bin/python
"""                                                                            
Proxy between zmq and websocket

"""
from websocket_server import WebsocketServer
import zmq
import argparse
import json
import ast
import mido
import base64

def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    arg = parser.add_argument

    arg('-i', '--data-bus-in',
        dest='data_bus_in',
        default='ipc:///tmp/data_bus_proxy_out',
        help='path to input socket')

    arg('-o', '--data-bus-out',
        dest='data_bus_out',
        default='ipc:///tmp/data_bus_proxy_in',
        help='path to output socket')

    arg('-q', '--quiet',
        dest='quiet',
        action='store_true',
        default=False,
        help='print nothing')

    return parser.parse_args()


# Called for every client connecting (after handshake)
def new_client(client, server):
    global websocket_ctrl_client
    global websocket_midi_client
    print("New client connected and was given id %d" % client['id'])
    if websocket_ctrl_client == None:
        websocket_ctrl_client = client
    else:
        websocket_midi_client = client


# Called for every client disconnecting
def client_left(client, server):
    global websocket_ctrl_client
    global websocket_midi_client
    print("Client(%d) disconnected" % client['id'])
    if client['id'] == websocket_ctrl_client['id']:
        websocket_ctrl_client = None
    else:
        websocket_midi_client = None
        


# Called when a client sends a message
def message_received(client, server, json_message):
    message = ast.literal_eval(json_message)
    print("Client(%d): %s" % (client['id'], repr(message)))
    if client['id'] == 1:
        handle_client_ctrl_message(message)
    else:
        handle_client_midi_message(message)

def handle_client_ctrl_message(message):
    global pub_socket
    global ctrl_socket
    global midi_socket
    msg = message['msg']
    if msg['command'] == 'subscribe':
        if msg['type'] == 'ctrl':
            print('subscribing ctrl_socket to ' + repr(message['topic']))
            subscribe(ctrl_socket, message['topic'])
        elif msg['type'] == 'midi':
            print('subscribing midi_socket to ' + repr(message['topic']))
            subscribe(midi_socket, message['topic'])
    elif msg['command'] == 'file':
        print ('got file')
        decoded = base64.decodestring(msg['content'])
        midi_file = mido.MidiFile(file=decoded)
        print('midi file ' + repr(midi_file))
    else:
        print('sending ctrl message to bus')
        send_ctrl_msg(pub_socket, message['topic'], message['msg'])
    
def handle_client_midi_message(message):
    global pub_socket
    print('sending midi message to bus')
    send_midi_msg(pub_socket, message['topic'], message['msg'])
    
def send_ctrl_msg(socket, topic, ctrl_msg):
    print('Sending ctrl message [' + repr(topic) + '] ' + repr(ctrl_msg))
    socket.send_string(topic, flags=zmq.SNDMORE)
    socket.send_pyobj(ctrl_msg)        

def send_midi_msg(socket, topic, ctrl_msg):
    print('Sending ctrl message [' + repr(topic) + '] ' + repr(ctrl_msg))
    socket.send_string(topic, flags=zmq.SNDMORE)
    socket.send_pyobj(ctrl_msg)        

def connect_subscriber(path):
    context = zmq.Context()
    socket = context.socket(zmq.SUB)
    socket.connect (path)
    return socket

def connect_publisher(path):
    context = zmq.Context()
    socket = context.socket(zmq.PUB)
    socket.connect (path)
    return socket

def subscribe(socket, topic):
    socket.setsockopt(zmq.SUBSCRIBE, topic)

def handle_ctrl_msg(topic, msg, server):
    global websocket_ctrl_client
    print('Got ctrl message')
    print('topic ' + repr(topic) + ' msg ' + repr(msg))
    if websocket_ctrl_client == None:
        print ('websocket_ctrl_client not connected, discarding')
        return
    message = {'topic' : topic, 'msg' : msg}
    json_message = json.dumps(message)
    print ('sending to websocket_ctrl_client')
    server.send_message(websocket_ctrl_client, json_message)

def handle_midi_msg(topic, msg, server):
    global websocket_midi_client
    print('Got midi message')
    print('topic ' + repr(topic) + ' msg ' + repr(msg))
    if websocket_midi_client == None:
        print ('websocket_midi_client not connected, discarding')
        return
    message = {'topic' : topic, 'msg' : msg.dict()}
    print('message ' + repr(message))
    json_message = json.dumps(message)
    print('json_message ' + repr(json_message))
    print ('sending to websocket_midi_client')
    server.send_message(websocket_midi_client, json_message)

def main():
    global pub_socket
    global midi_socket
    global ctrl_socket
    global websocket_ctrl_client
    global websocket_midi_client
    
    websocket_ctrl_client = None
    websocket_midi_client = None

    ctrl_socket = connect_subscriber(args.data_bus_in)
    midi_socket = connect_subscriber(args.data_bus_in)
    pub_socket = connect_publisher(args.data_bus_out)
    
    subscribe(ctrl_socket, 'all')
    subscribe(ctrl_socket, 'server')

    PORT=9001
    server = WebsocketServer(PORT)
    server.set_fn_new_client(new_client)
    server.set_fn_client_left(client_left)
    server.set_fn_message_received(message_received)

    subpoller = zmq.Poller()
    server_fileno = server.fileno()
    subpoller.register(ctrl_socket, zmq.POLLIN)
    subpoller.register(midi_socket, zmq.POLLIN)
    subpoller.register(server_fileno, zmq.POLLIN)
    
    while 1:
        try:
            clientsock = dict(subpoller.poll(None))

            if clientsock:
                if ctrl_socket in clientsock and clientsock[ctrl_socket] == zmq.POLLIN:
                    topic = ctrl_socket.recv()
                    ctrl_msg = ctrl_socket.recv_pyobj()
                    handle_ctrl_msg(topic, ctrl_msg, server)
                if midi_socket in clientsock and clientsock[midi_socket] == zmq.POLLIN:
                    topic = midi_socket.recv()
                    midi_msg = midi_socket.recv_pyobj()
                    handle_midi_msg(topic, midi_msg, server)
                if server_fileno in clientsock and clientsock[server_fileno] == zmq.POLLIN:
                    server._handle_request_noblock()
        except:
            print('got exception')
            exit(0)


args = parse_args()


main()
