#!/usr/bin/python
"""                                                                            
Midi editor

"""
from Tkinter import *
import mido
import zmq
import sys
import argparse
from funk_root import root
import funk_zmq
import funk_files
import funk_ctrl
import funk_ticker

def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    arg = parser.add_argument

    arg('-i', '--data-bus-in',
        dest='data_bus_in',
        default='ipc:///tmp/data_bus_proxy_out',
        help='path to input socket')

    arg('-o', '--data-bus-out',
        dest='data_bus_out',
        default='ipc:///tmp/data_bus_proxy_in',
        help='path to output socket')

    return parser.parse_args()


def About():
    print("This is a simple example of a menu")


args = parse_args()

funk_ctrl.midi_socket = funk_zmq.connect_subscriber(args.data_bus_in)
funk_ctrl.ctrl_socket = funk_zmq.connect_subscriber(args.data_bus_in)
funk_ctrl.pub_socket = funk_zmq.connect_publisher(args.data_bus_out)
    
funk_zmq.subscribe(funk_ctrl.ctrl_socket, 'all')
funk_zmq.subscribe(funk_ctrl.midi_socket, 'recorded')
funk_zmq.subscribe(funk_ctrl.midi_socket, 'time')
funk_zmq.register_poller([funk_ctrl.ctrl_socket, funk_ctrl.midi_socket])

width = root.winfo_screenwidth()
height = root.winfo_screenheight()

root.geometry('%dx%d' % (width, height/2))
root.title("Forget Jazz, here is Funk!")

menu = Menu(root)
filemenu = Menu(menu)
menu.add_cascade(label="File", menu=filemenu)
filemenu.add_command(label="New", command=funk_files.NewFile)
filemenu.add_command(label="Open...", command=funk_files.OpenFile)
filemenu.add_command(label="Play", command=funk_ctrl.midi_start_play_file)
filemenu.add_command(label="Record", command=funk_ctrl.midi_start_play_record_file)
filemenu.add_command(label="Stop", command=funk_ctrl.midi_stop_play)
filemenu.add_command(label="Mute/unmute drum channel", command=funk_ctrl.midi_mute_unmute_channel)
filemenu.add_command(label="Mute/unmute perc track", command=funk_ctrl.midi_mute_unmute_track)
filemenu.add_command(label="Panic", command=funk_ctrl.midi_panic)
filemenu.add_command(label="Reset", command=funk_ctrl.midi_reset)
filemenu.add_command(label="Quit", command=funk_ctrl.all_quit)
filemenu.add_separator()
filemenu.add_command(label="Exit", command=root.quit)

helpmenu = Menu(menu)
menu.add_cascade(label="Help", menu=helpmenu)
helpmenu.add_command(label="About...", command=About)

toolbar = Frame(root)

b = Button(toolbar, text="new", width=6, command=funk_files.NewFile)
b.pack(side=LEFT, padx=2, pady=2)
b = Button(toolbar, text="open", width=6, command=funk_files.OpenFile)
b.pack(side=LEFT, padx=2, pady=2)
b = Button(toolbar, text="play", width=6, command=funk_ctrl.midi_start_play_file)
b.pack(side=LEFT, padx=2, pady=2)
b = Button(toolbar, text="rec", width=6, command=funk_ctrl.midi_start_play_record_file)
b.pack(side=LEFT, padx=2, pady=2)
b = Button(toolbar, text="stop", width=6, command=funk_ctrl.midi_stop_play)
b.pack(side=LEFT, padx=2, pady=2)
b = Button(toolbar, text="panic", width=6, command=funk_ctrl.midi_panic)
b.pack(side=RIGHT, padx=2, pady=2)
b = Button(toolbar, text="exit", width=6, command=root.quit)
b.pack(side=RIGHT, padx=2, pady=2)

toolbar.pack(side=TOP, fill=X)

root.config(menu=menu)

root.after(100, funk_ticker.task)

mainloop()
